# ===============================
# BASIC CONFIG
# ===============================
spring.application.name=cis-api
server.port=8082
server.servlet.context-path=/cis-api

# ===============================
# EUREKA CONFIG
# ===============================
eureka.client.service-url.defaultZone=${EUREKA_URL}

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# ===============================
# DATABASE (MATCH ASSET SERVICE)
# ===============================

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}


# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# IMPORTANT (you missed this)
spring.jpa.properties.hibernate.default_schema=kranmaster

# ===============================
# HIBERNATE LOGGING
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# ===============================
# DEBUG & LOGGING
# ===============================
debug=true
logging.level.org.springframework.security=DEBUG

# ===============================
# FILE UPLOAD
# ===============================
spring.servlet.multipart.max-request-size=20MB
spring.servlet.multipart.max-file-size=20MB

# ===============================
# ERROR PAGE
# ===============================
server.error.whitelabel.enabled=true